[package]
name = "promising-future"
version = "0.1.0"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
license = "MIT"
description = "Implementation of Promise/Future pairs."
repository = "https://github.com/jsgf/promising-future"
readme = "README.md"
keywords = ["async", "asynchronous", "promise", "future"]
